-- ERSATT – kör inte denna fil.
--
-- Den tidigare versionen gav anon-nyckeln full läs- och skrivrätt till alla
-- tabeller (protokoll med personnummer m.m.). Databasschemat och de låsta
-- RLS-policyerna finns nu i:
--
--   supabase/migrations/001_auth_och_rls.sql
